services:
  Game-master-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/tinlas03-2025-vt/game-master:latest
    container_name: Game-master-local
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - NODE_NAME=game_master
      - COUNTER_TOPIC=/game_master/counter
      - HEARTBEAT_TOPIC=/game_master/heartbeat
      - INPUT_TOPIC=/game_master/input
      - ROBOTS_POS_TOPIC=/robots/pos
      - TIMER_PERIOD_SEC=1.0
      - RELIABLE_QOS=true
    command: >
      bash -lc "
      source /opt/ros/humble/setup.bash &&
      exec python3 src/game_master_node.py
      "
